### ISSUE TITLE
FR1.  Click Pins For Preview

### ISSUE THREAD

**Issue by CarbonatedSoftDrink** [WSU-4110/Eventsly#1]
| FR1.  Click Pins For Preview |
| ------------- |
| **Goal**: The user can click on even pins for a preview of the event.  |
| **Stakeholders**: Users  |
| **Description**: When the map loads on the screen, the user can click a pin to get a pop-up screen that will show a preview of the event. The preview of the event will include only the title, location, date, and time of the event. When the preview cannot load, an error message will show. |
| **Origin**: Based on our 9/28 meeting. The team discussed how we want to show initial information as opposed to detailed information about events. |
| **Version**: 1.0 |
| **Date**:  09/28/2021 |
| **Priority**: 1 |

**Comment by cj-fox** [comment]
Implemented with [PR #44](https://github.com/WSU-4110/Eventsly/pull/44)
