### ISSUE TITLE
FR12.  Store User Bookmarked Events

### ISSUE THREAD

**Issue by CarbonatedSoftDrink** [WSU-4110/Eventsly#12]
| FR12.  Store User Bookmarked Events |
| --- |
| **Goal**: The Application Server will store events selected by users into their bookmarks |
| **Stakeholders**: Application Server |
| **Description**: The application server must store events that a user with an account bookmarks. The bookmarks must be linked to an account. A user will also be able to un-bookmark events. The application server will reflect the removal of the event from the bookmark list. When the application server has already bookmarked 15 events for a user and the user attempts to bookmark an additional event, the application server will produce an error.|
| **Origin**: Based on the initial project proposal, the team leader described this functionality in our first meeting. |
| **Version**: 1.0 |
| **Date**: 09/28/2021 |
| **Priority**: 3 |

**Comment by cj-fox** [comment]
Closing issue because it is a duplicate requirement.
