### ISSUE TITLE
FR14.  Load Event Pins

### ISSUE THREAD

**Issue by CarbonatedSoftDrink** [WSU-4110/Eventsly#14]
| FR14.  Load Event Pins |
| --- |
| **Goal**: The application will load the created event pins on the map |
| **Stakeholders**: Application Server |
| **Description**: When the user opens the web application, a map of the surrounding area will load. All previously created event pins will load onto the map.  When the pins do not automatically populate onto the map the application will ask the user to share their location with the application. When the pins on the map do not load within 30 seconds an offline error will be presented to the user. |
| **Origin**: Based on the initial project proposal, the team leader described this functionality in our first meeting. |
| **Version**: 1.0 |
| **Date**:  09/28/2021 |
| **Priority**: 1 |

**Comment by cj-fox** [comment]
Implemented with [PR #44](https://github.com/WSU-4110/Eventsly/pull/44)
