### ISSUE TITLE
FR2.  Expand pop-up page

### ISSUE THREAD

**Issue by CarbonatedSoftDrink** [WSU-4110/Eventsly#2]
| FR2.  Expand pop-up page |
| ---------------------|
| **Goal**: The application will allow users to expand the event preview pop-up to learn more information about the event. |
| **Stakeholders**: Users |
| **Description**: After interacting with an event pin, once the event preview pop-up displays, the user will be given an option to expand the preview.  When the user clicks to expand the preview, they will be taken to a different page that shows all the event details that were provided by the event organizer. When the full event detail page can’t load, an error message will show. |
| **Origin**: Based on our 9/28 meeting. The team discussed how we want to show initial information as opposed to detailed information about events. |
| **Version**: 1.0 |
| **Date**:  09/28/2021 |
| **Priority**: 1 |

**Comment by slattery-mark** [comment]
Completed with [PR #62](https://github.com/WSU-4110/Eventsly/pull/62)
