### ISSUE TITLE
NR5. Display Usability

### ISSUE THREAD

**Issue by cj-fox** [WSU-4110/Eventsly#20]
| NR5. Display Usability |
| --- |
| **Goal**: Adjust display to improve ease of use. |
| **Stakeholders**: All |
| **Description**: When users open the application, the application will automatically resize accordingly based on the device that the user is utilizing. |
| **Origin**: Based on our 9/28 meeting. The team discussed details about usability across devices. |
| **Version**: 1.0 |
| **Date**:  09/28/2021 |
| **Priority**: 4 |

**Comment by slattery-mark** [comment]
Completed with [PR #60](https://github.com/WSU-4110/Eventsly/pull/60) which ensured every page is responsive according to screen size.
