### ISSUE TITLE
FR11. Remove Expired Events From Map

### ISSUE THREAD

**Issue by slattery-mark** [WSU-4110/Eventsly#27]
| FR11. Remove Expired Events From Map |
| --- |
| **Goal**: Events that have existed past their date will be removed from the map.  |
| **Stakeholders**: Application Server |
| **Description**: Once an event passes the date that it takes place on, the event will remove itself from the map on the home page, but the events will stay inside the application server as expired. The pin of the event and the event details will no longer be viewable by users. |
| **Origin**: Based on tour 10/5 meeting. The team discussed removing expired events to prevent the map from being cluttered. |
| **Version**: 1.0 |
| **Date**:  10/5/2021 |
| **Priority**: 2 |

**Comment by cj-fox** [comment]
Implemented with [PR #44](https://github.com/WSU-4110/Eventsly/pull/44)
