### ISSUE TITLE
FR12. Delete Account

### ISSUE THREAD

**Issue by slattery-mark** [WSU-4110/Eventsly#28]
| FR12. Delete Account |
| --- |
| **Goal**: Users with accounts must be able to delete their own account.  |
| **Stakeholders**: Users |
| **Description**: A user with an account must be able to delete their own account. When they delete their account, they will no longer be able to log in to the account. |
| **Origin**: Based on tour 10/5 meeting. The team discussed adding the delete feature for user accounts. |
| **Version**: 1.0 |
| **Date**:  10/05/2021 |
| **Priority**: 5 |

**Comment by cj-fox** [comment]
Implemented with [PR#51](https://github.com/WSU-4110/Eventsly/pull/51)
