### ISSUE TITLE
FR3.  Account registration

### ISSUE THREAD

**Issue by CarbonatedSoftDrink** [WSU-4110/Eventsly#3]
| FR3.  Account registration |
|----|
| **Goal**: The application must allow users to sign up for an account. |
| **Stakeholders**: Users |
| **Description**: When a user accesses the application, the application must provide an option to sign up for an account. If the user chooses to sign up, a sign-up page will be displayed. The user must provide their first and last name, email address, and phone number. They must also create a username. The email address and username must not have already been used to sign up for an account. When the username and/or email address provided have already been used to sign up for an account, the user will be prompted to enter a different email address and/or username. The user must also create a password that meets industry standard password complexity guidelines. When the password provided does not meet industry standard complexity guidelines, the user will be prompted to create a different password. When the user provides information that meets all requirements, the application will inform the user that they signed up successfully. |
| **Origin**: Based on the initial project proposal, the team leader described this functionality in our first meeting. |
| **Version**: 1.0 |
| **Date**:  09/28/2021 |
| **Priority**: 2 |

**Comment by cj-fox** [comment]
Feature has been implemented.
