### ISSUE TITLE
FR18. About Us

### ISSUE THREAD

**Issue by cj-fox** [WSU-4110/Eventsly#52]
| FR18. About Us|
| --- |
| **Goal**: Users should be able to navigate to a page describing the application  |
| **Stakeholders**: Users |
| **Description**: From the navigation bar, any user that visits the application must be able to navigate to an About Us page that gives information about the application and the contributors. |
| **Origin**: Based on tour 11/2 meeting. The team discussed additional features to add as we enter Sprint 3. |
| **Version**: 1.0 |
| **Date**:  11/2/2021 |
| **Priority**: 5 |

**Comment by Racquel2021** [comment]
Implemented with PR #45

**Comment by Racquel2021** [comment]
Implemented with PR #45
