### ISSUE TITLE
NR10. Frontend Maintainability

### ISSUE THREAD

**Issue by cj-fox** [WSU-4110/Eventsly#53]
| NR10. Frontend Maintainability|
| --- |
| **Goal**:  Frontend code should be easily maintainable..  |
| **Stakeholders**: Developers|
| **Description**: Frontend code should be written following HTML/CSS guidelines to improve maintainability and enhance the ability to refactor code. |
| **Origin**: Based on tour 11/2 meeting. The team discussed additional features to add as we enter Sprint 3. |
| **Version**: 1.0 |
| **Date**:  11/2/2021 |
| **Priority**: 1 |

**Comment by slattery-mark** [comment]
`[PR #48](https://github.com/WSU-4110/Eventsly/pull/48)` included a massive refactoring which brought the frontend code in line with the project's stated [Frontend Convetions](https://github.com/WSU-4110/Eventsly/wiki/Frontend-Conventions). This NR will include continued adherence to those guidelines until project completion.

**Comment by slattery-mark** [comment]
Completed with [PR #60](https://github.com/WSU-4110/Eventsly/pull/60) which ensured all stylesheets follow consistent guidelines outlined on our [best practices](https://github.com/WSU-4110/Eventsly/wiki/Best-Practices-and-Team-Guidelines) page and implemented easily maintainable design patterns where applicable.
