### ISSUE TITLE
NR11. Form Usability

### ISSUE THREAD

**Issue by cj-fox** [WSU-4110/Eventsly#54]
| NR10. Form Usability|
| --- |
| **Goal**:   Consistent display of forms |
| **Stakeholders**: Users |
| **Description**: Application forms should be displayed in the same way to provide visual indication of the functionality to users. |
| **Origin**: Based on our 11/2 meeting. The team discussed additional features to add as we enter Sprint 3. |
| **Version**: 1.0 |
| **Date**:  11/2/2021 |
| **Priority**: 1 |

**Comment by slattery-mark** [comment]
All forms use a consistent style as of [PR #11](https://github.com/WSU-4110/Eventsly/pull/59) and all forms which require validation use the same visual cues and have the same functionality.
