### ISSUE TITLE
FR9.  Edit event information

### ISSUE THREAD

**Issue by CarbonatedSoftDrink** [WSU-4110/Eventsly#9]
| FR9.  Edit event information |
| --- |
| **Goal**: An event organizer can edit their event’s details. |
| **Stakeholders**: Users |
| **Description**: After creating an event, the event organizer can edit that event’s details at any point before the event occurs. When an event organizer chooses to edit an event’s details, they will be able to either save their changes or discard them. When they save the changes, their event’s details will be updated with their edits. When they discard the changes, the event’s details will not change from their previously saved state. |
| **Origin**: Based on the team’s meeting on 9/28.  The team decided that it would be best to provide editing abilities to avoid deletion/recreation of events. |
| **Version**: 1.0 |
| **Date**: 09/28/2021 |
| **Priority**: 3 |

**Comment by cj-fox** [comment]
Implemented with [PR#63](https://github.com/WSU-4110/Eventsly/pull/63)
